#ifndef INTERUPT_SERVICE_ROUTINE_H_INCLUDED
#define INTERUPT_SERVICE_ROUTINE_H_INCLUDED

#include <RnKernel.h>

RnResult RN_API RnInteruptServiceRoutineInitialize();

#endif //!INTERUPT_SERVICE_ROUTINE_H_INCLUDED
